apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-car
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-car
  template:
    metadata:
      labels:
        app: dummy-car
    spec:
      containers:
      - name: dummy-car
        image: ghcr.io/tbhuvaneswar/dummy-car:latest
        ports:
        - containerPort: 8080
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: dummy-car-config
              key: APP_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: dummy-car-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: dummy-car-config
              key: DB_NAME
